# Generated by Django 3.0.6 on 2020-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('list_content', models.TextField(max_length=45)),
                ('not_to_done', models.BooleanField(default=False)),
            ],
        ),
    ]
