# Generated by Django 3.0.6 on 2020-06-23 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='last_date_to_done',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 12, 51, 6, 667786)),
        ),
    ]
