# Generated by Django 3.0.6 on 2020-06-23 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0002_todo_last_date_to_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='not_to_done',
            new_name='done',
        ),
        migrations.AlterField(
            model_name='todo',
            name='last_date_to_done',
            field=models.DateField(default=datetime.datetime(2020, 6, 23, 12, 56, 15, 573358)),
        ),
    ]
