# Generated by Django 3.0.6 on 2020-06-23 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0003_auto_20200623_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_date_to_done',
            field=models.DateField(default=datetime.date(2020, 6, 23)),
        ),
    ]
