# Generated by Django 3.0.6 on 2020-06-24 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0004_auto_20200623_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='list_content',
            new_name='todo_item',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='last_date_to_done',
        ),
        migrations.AddField(
            model_name='todo',
            name='lastdate',
            field=models.DateField(default=datetime.date(2020, 6, 24)),
        ),
    ]
